sudo: true

language: c

install: 
  - sudo apt-get install swig
  - cd ..
  - git clone https://github.com/mozilla/sphinxbase
  - cd sphinxbase
  - ./autogen.sh
  - ./configure && make && make install
  - cd ../pocketsphinx
  - ./autogen.sh
  - ./configure
  - make
  - make install
